<?php
/**
 * @file
 * Code for the Feature Context Base feature.
 */

include_once 'feature_context_base.features.inc';

/**
 * Implements hook_block_view_alter().
 */
function feature_context_base_block_view_alter(&$data, $block) {
  $no_title_blocks = array(
    'system' => array(
      'main-menu',
    ),
    'menu' => array(
      'menu-footer-menu',
    ),
    'menu_block' => array(
      'visustock-second-level',
    ),
  );
  if (!empty($no_title_blocks[$block->module]) && in_array($block->delta, $no_title_blocks[$block->module])) {
    $data['subject'] = '';
  }
}

/**
 * Implements hook_menu_block_blocks().
 */
function feature_context_base_menu_block_blocks() {
  return array(
    // The array key is the block id used by menu block.
    'visustock-second-level' => array(
      // Use the array keys/values described in menu_tree_build().
      'menu_name'   => MENU_TREE__CURRENT_PAGE_MENU,
      'parent_mlid' => 0,
      'title_link'  => FALSE,
      'admin_title' => 'Block main second level',
      'level'       => 2,
      'follow'      => 1,
      'depth'       => -1,
      'expanded'    => TRUE,
      'sort'        => FALSE,
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function feature_context_base_block_info() {
  return array(
    'visustock-header-title' => array(
      'info' => 'Header title',
    ),
    'visustock-spacer' => array(
      'info' => 'Spacer',
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function feature_context_base_block_view($delta = '') {
  $block = array();
  if ($delta == 'visustock-header-title') {
    $block['subject'] = '';
    $block['content'] = _feature_context_header_title();
  }
  elseif ($delta == 'visustock-spacer') {
    $block['subject'] = '';
    $block['content'] = '&nbsp;';
  }
  return $block;
}

/**
 * Header title block content callback.
 */
function _feature_context_header_title() {
  global $theme_key;
  if ($theme_key == variable_get('admin_theme', '')) {
    return '';
  }

  $result = '';
  $wrapper = &drupal_static('feature_context_header_title_wrapper', 'h2');
  $attr = array();
  $menu = menu_get_active_trail();

  $item = FALSE;
  $title_callback_args = array();
  if (!empty($menu[1]['link_path']) && substr($menu[1]['link_path'], 0, 1) != '<') {
    $item = menu_get_item($menu[1]['link_path']);
    if ($item) {
      $title_callback_args = menu_unserialize($item['title_arguments'], $item['map']);
    }
  }

  // The current page is a root or is not in a menu
  if (count($menu) == 2) {
    // Special case for news nodes
    if (!empty($menu[1]['map']) && $menu[1]['map'][0] == 'node' && $menu[1]['map'][1]->type == 'news') {
      $result = 'Toutes les actualités';
    }
    // Other nodes or lonely pages
    else {
      $result = drupal_get_title();
      $wrapper = 'h1';
      $attr['class'] = 'title';
      $attr['id'] = 'page-title';
      // Clear the title to avoid duplicated h1 in the page
      if (function_exists('alpha_get_theme')) {
        $theme = alpha_get_theme();
        $theme->settings['toggle']['page_title'] = 0;
      }
    }
  }
  // If a router item exists, use it
  elseif ($item) {
    if ($item['title_callback'] == 't' && empty($title_callback_args)) {
      $result = t($item['title']);
    }
    else {
      $result = call_user_func_array($item['title_callback'], $title_callback_args);
    }
  }
  // If no router item exists, just keep the title
  else {
    $result = $menu[1]['title'];
  }

  // Prepare the result
  if (!empty($result)) {
    $result = '<' . $wrapper . drupal_attributes($attr) . '>' . $result . '</' . $wrapper . '>';
  }

  return $result;
}

/**
 * Implements hook_preprocess_html().
 */
function feature_context_base_preprocess_html(&$variables) {
  $wrapper = &drupal_static('feature_context_header_title_wrapper', FALSE);
  if ($wrapper !== FALSE) {
    $variables['classes_array'][] = 'visustock-wrapped-' . $wrapper;
  }
}
