<?php
/**
 * @file
 * Code for the VisuStock Forms module.
 */

define('VISUSTOCK_FORMS_APP_URL_DEFAULT', 'http://test.visustock.fr/app');
define('VISUSTOCK_FORMS_APP_URL_LOGGED', VISUSTOCK_FORMS_APP_URL_DEFAULT . '/index.php');

/**
 * Implements hook_menu().
 */
function visustock_forms_menu() {
  $items = array();

  $items['login'] = array(
    'title' => t('Connexion'),
    'page callback' => '_visustock_forms_login',
    'access callback' => TRUE,
  );
  $items['lost-password'] = array(
    'title' => t('Récupération de compte'),
    'page callback' => '_visustock_forms_pass',
    'access callback' => TRUE,
  );
  $items['retrieve-password'] = array(
    'title' => t('Récupération de compte'),
    'page callback' => '_visustock_forms_pass2',
    'access callback' => TRUE,
  );
  $items['register'] = array(
    'title' => t('Demande de compte démo'),
    'page callback' => '_visustock_forms_register',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Page visustock/login callback
 */
function _visustock_forms_login() {
  $result = _visustock_forms_commons();
  $key = variable_get('css_js_query_string', time());
  drupal_add_css(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/resources/css/login.css?' . $key, array('type' => 'external'));
  drupal_add_js(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/login-all.js?' . $key, 'external');

  $result['lost'] = array(
    '#markup' => '<p><a href="' . url('lost-password') . '" class="lost-password-link">Vous ne pouvez accéder à votre compte ?</a></p>',
    '#weight' => 1,
  );

  return $result;
}

/**
 * Page visustock/lost-password callback
 */
function _visustock_forms_pass() {
  $result = _visustock_forms_commons();
  $key = variable_get('css_js_query_string', time());
  drupal_add_css(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/resources/css/visustock.css?' . $key, array('type' => 'external'));
  drupal_add_css(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/resources/css/login.css?' . $key, array('type' => 'external'));
  drupal_add_js(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/lost-password-all.js?' . $key, 'external');
  return $result;
}

/**
 * Page visustock/retrieve-password callback
 */
function _visustock_forms_pass2() {
  // Test key validity
  $key = isset($_GET['h']) ? $_GET['h'] : '';
  $url = url(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/recoverPassStep2TestHash.php', array('external' => TRUE, 'query' => array('h' => $key)));
  $result = drupal_http_request($url);
  if ($result->data == 0) {
    return array(
      '#markup' => '<p>Erreur:</p><p>Le lien fourni n\'est plus valide.</p><p>Si vous devez réinitialiser votre mot de passe, veuillez cliquer sur le lien ci-dessous.</p><p><a href="' . url('lost-password') . '">>Réinitialiser votre mot de passe</a></p>',
    );
  }

  $result = _visustock_forms_commons();
  $key = variable_get('css_js_query_string', time());
  drupal_add_css(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/resources/css/visustock.css?' . $key, array('type' => 'external'));
  drupal_add_css(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/resources/css/login.css?' . $key, array('type' => 'external'));
  drupal_add_js(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/retrieve-password-all.js?' . $key, 'external');
  drupal_add_js(array('visustock' => array('h' => $_GET['h'])), 'setting');
  return $result;
}

/**
 * Page visustock/register callback
 */
function _visustock_forms_register() {
  $result = _visustock_forms_commons();
  $key = variable_get('css_js_query_string', time());
  drupal_add_css(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/resources/css/visustock.css?' . $key, array('type' => 'external'));
  drupal_add_css(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/resources/css/login.css?' . $key, array('type' => 'external'));
  drupal_add_js(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/register-all.js?' . $key, 'external');
  return $result;
}

/**
 * Pages commons helper
 */
function _visustock_forms_commons() {
  // Test if user is already logged in
  $url = url(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/loginTest.php', array('external' => TRUE));
  $result = drupal_http_request($url, array('headers' => array('Cookie' => 'VSSID=' . $_COOKIE['VSSID'])));
  if ($result->data == 1) {
    $url = url(VISUSTOCK_FORMS_APP_URL_LOGGED, array('external' => TRUE));
    drupal_goto($url);
  }

  $key = variable_get('css_js_query_string', time());
  drupal_add_css(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/extjs/resources/css/ext-all.css?' . $key, array('type' => 'external'));
  drupal_add_js(VISUSTOCK_FORMS_APP_URL_DEFAULT . '/extjs/ext.js?' . $key, 'external');
  return array(
    'form' => array(
      '#markup' => '<div id="theForm"></div>',
      '#weight' => 0,
    ),
  );
}
